FROM alpine:3.22

RUN apk update && apk add --no-cache \
	php83 \
	php83-fpm \
	php83-mysqli \
	php83-phar \
	php83-iconv \
	php83-mbstring \
	wget \
	ca-certificates \
	mariadb-client

RUN mkdir -p /var/www/wordpress

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x wp-cli.phar \
	&& mv wp-cli.phar /usr/local/bin/wp

COPY www.conf /etc/php83/php-fpm.d/www.conf

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 9000

WORKDIR /var/www/wordpress

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
